services:
  db:
    container_name: postgres-container
    image: postgres:18
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: go-api
    ports:
      - "8000:8080"
    depends_on:
      - db
    env_file:
      - .env

volumes:
  pgdata: {} # comment so some extension do not break indentation
